// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: author.proto

package authorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BecomeAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BecomeAuthorRequest) Reset() {
	*x = BecomeAuthorRequest{}
	mi := &file_author_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BecomeAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BecomeAuthorRequest) ProtoMessage() {}

func (x *BecomeAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_author_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BecomeAuthorRequest.ProtoReflect.Descriptor instead.
func (*BecomeAuthorRequest) Descriptor() ([]byte, []int) {
	return file_author_proto_rawDescGZIP(), []int{0}
}

func (x *BecomeAuthorRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AuthorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorResponse) Reset() {
	*x = AuthorResponse{}
	mi := &file_author_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorResponse) ProtoMessage() {}

func (x *AuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_author_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorResponse.ProtoReflect.Descriptor instead.
func (*AuthorResponse) Descriptor() ([]byte, []int) {
	return file_author_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuthorResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ValidateAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAuthorRequest) Reset() {
	*x = ValidateAuthorRequest{}
	mi := &file_author_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAuthorRequest) ProtoMessage() {}

func (x *ValidateAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_author_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAuthorRequest.ProtoReflect.Descriptor instead.
func (*ValidateAuthorRequest) Descriptor() ([]byte, []int) {
	return file_author_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateAuthorRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ValidateAuthorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAuthor      bool                   `protobuf:"varint,1,opt,name=is_author,json=isAuthor,proto3" json:"is_author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAuthorResponse) Reset() {
	*x = ValidateAuthorResponse{}
	mi := &file_author_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAuthorResponse) ProtoMessage() {}

func (x *ValidateAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_author_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAuthorResponse.ProtoReflect.Descriptor instead.
func (*ValidateAuthorResponse) Descriptor() ([]byte, []int) {
	return file_author_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateAuthorResponse) GetIsAuthor() bool {
	if x != nil {
		return x.IsAuthor
	}
	return false
}

var File_author_proto protoreflect.FileDescriptor

const file_author_proto_rawDesc = "" +
	"\n" +
	"\fauthor.proto\x12\x06author\".\n" +
	"\x13BecomeAuthorRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"9\n" +
	"\x0eAuthorResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"0\n" +
	"\x15ValidateAuthorRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"5\n" +
	"\x16ValidateAuthorResponse\x12\x1b\n" +
	"\tis_author\x18\x01 \x01(\bR\bisAuthor2\xa5\x01\n" +
	"\rAuthorService\x12C\n" +
	"\fBecomeAuthor\x12\x1b.author.BecomeAuthorRequest\x1a\x16.author.AuthorResponse\x12O\n" +
	"\x0eValidateAuthor\x12\x1d.author.ValidateAuthorRequest\x1a\x1e.author.ValidateAuthorResponseB\x10Z\x0eproto/authorpbb\x06proto3"

var (
	file_author_proto_rawDescOnce sync.Once
	file_author_proto_rawDescData []byte
)

func file_author_proto_rawDescGZIP() []byte {
	file_author_proto_rawDescOnce.Do(func() {
		file_author_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_author_proto_rawDesc), len(file_author_proto_rawDesc)))
	})
	return file_author_proto_rawDescData
}

var file_author_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_author_proto_goTypes = []any{
	(*BecomeAuthorRequest)(nil),    // 0: author.BecomeAuthorRequest
	(*AuthorResponse)(nil),         // 1: author.AuthorResponse
	(*ValidateAuthorRequest)(nil),  // 2: author.ValidateAuthorRequest
	(*ValidateAuthorResponse)(nil), // 3: author.ValidateAuthorResponse
}
var file_author_proto_depIdxs = []int32{
	0, // 0: author.AuthorService.BecomeAuthor:input_type -> author.BecomeAuthorRequest
	2, // 1: author.AuthorService.ValidateAuthor:input_type -> author.ValidateAuthorRequest
	1, // 2: author.AuthorService.BecomeAuthor:output_type -> author.AuthorResponse
	3, // 3: author.AuthorService.ValidateAuthor:output_type -> author.ValidateAuthorResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_author_proto_init() }
func file_author_proto_init() {
	if File_author_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_author_proto_rawDesc), len(file_author_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_author_proto_goTypes,
		DependencyIndexes: file_author_proto_depIdxs,
		MessageInfos:      file_author_proto_msgTypes,
	}.Build()
	File_author_proto = out.File
	file_author_proto_goTypes = nil
	file_author_proto_depIdxs = nil
}
